// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"t02/entity"
)

// Injectors from wire.go:

func InitializeEvent(phrase string) (entity.Event, error) {
	message := entity.NewMessage(phrase)
	greeter := entity.NewGreeter(message)
	event, err := entity.NewEvent(greeter)
	if err != nil {
		return entity.Event{}, err
	}
	return event, nil
}
