// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"context"
	"wire_sample2/entity"
)

// Injectors from injector.go:

func setUp(ctx context.Context, name string) (entity.Foo, error) {
	foo := entity.ProviderFoo(name)
	return foo, nil
}
