// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"context"
)

// Injectors from injector.go:

func setUp(ctx context.Context, name string) (Foo, error) {
	foo := ProviderFoo(name)
	return foo, nil
}
